{
   parserClass="com.tecknobit.envui.ide.envfile.EnvParser"
   psiPackage="com.tecknobit.envui.ide.envfile"
  extends="com.intellij.lang.parser.GeneratedParserUtilBase"
}

file ::= statement*

statement ::= property | comment | empty_line

property ::= key "=" value

key ::= KEY

value ::= VALUE | QUOTED_VALUE

comment ::= COMMENT

empty_line ::= NEW_LINE